# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19eprdh9YgYzayazZJf0OA7wJqs6htES7
"""

import datetime
class agecalender:
  count=0
  def __init__(self):
   pass

  def age_calculation(self):
    print("please enter your birth year")
    birthdate_string= input()
    try:
      birth_date=datetime.datetime.strptime(birthdate_string, "%m/%d/%Y")
      if 1<= birth_date .day <=31 and 1<= birth_date.month<=12 :
        this_year = int(datetime.datetime.now().year)
        real_age= (this_year)-(birth_date.year)
        return real_age

    except ValueError as e:
            print(f"Error: {e}")


new_person_age = agecalender()
new_person_age.age_calculation()